/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IABIResolver } from "./IABIResolver";
export type { IAddrResolver } from "./IAddrResolver";
export type { IAddressResolver } from "./IAddressResolver";
export type { IContentHashResolver } from "./IContentHashResolver";
export type { IDNSRecordResolver } from "./IDNSRecordResolver";
export type { IDNSZoneResolver } from "./IDNSZoneResolver";
export type { IExtendedResolver } from "./IExtendedResolver";
export type { IInterfaceResolver } from "./IInterfaceResolver";
export type { INameResolver } from "./INameResolver";
export type { IPubkeyResolver } from "./IPubkeyResolver";
export type { ITextResolver } from "./ITextResolver";
