/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  AddressSet,
  AddressSetInterface,
} from "../../../../contracts/keyring/lib/AddressSet";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "module",
        type: "string",
      },
      {
        internalType: "string",
        name: "method",
        type: "string",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
      {
        internalType: "string",
        name: "context",
        type: "string",
      },
    ],
    name: "AddressSetConsistency",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122088672bf2a58c1225b899cd33737488a66a25836f7960b56446b58c3945aee38664736f6c634300080e0033";

type AddressSetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AddressSetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AddressSet__factory extends ContractFactory {
  constructor(...args: AddressSetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "AddressSet";
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AddressSet> {
    return super.deploy(overrides || {}) as Promise<AddressSet>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AddressSet {
    return super.attach(address) as AddressSet;
  }
  override connect(signer: Signer): AddressSet__factory {
    return super.connect(signer) as AddressSet__factory;
  }
  static readonly contractName: "AddressSet";

  public readonly contractName: "AddressSet";

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AddressSetInterface {
    return new utils.Interface(_abi) as AddressSetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AddressSet {
    return new Contract(address, _abi, signerOrProvider) as AddressSet;
  }
}
