/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IExtendedResolver,
  IExtendedResolverInterface,
} from "../../../../../../@ensdomains/ens-contracts/contracts/resolvers/profiles/IExtendedResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "name",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "resolve",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IExtendedResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IExtendedResolverInterface {
    return new utils.Interface(_abi) as IExtendedResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExtendedResolver {
    return new Contract(address, _abi, signerOrProvider) as IExtendedResolver;
  }
}
