/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IIdentityMembershipProofVerifier,
  IIdentityMembershipProofVerifierInterface,
} from "../../../../contracts/keyring/interfaces/IIdentityMembershipProofVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[4]",
        name: "input",
        type: "uint256[4]",
      },
    ],
    name: "verifyProof",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIdentityMembershipProofVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IIdentityMembershipProofVerifierInterface {
    return new utils.Interface(
      _abi
    ) as IIdentityMembershipProofVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIdentityMembershipProofVerifier {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IIdentityMembershipProofVerifier;
  }
}
