/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKeyringZkVerifier,
  IKeyringZkVerifierInterface,
} from "../../../../contracts/keyring/interfaces/IKeyringZkVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "Unacceptable",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "deployer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "identityConstructionProofVerifier",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "membershipProofVerifier",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "authorisationProofVerifier",
        type: "address",
      },
    ],
    name: "Deployed",
    type: "event",
  },
  {
    inputs: [],
    name: "AUTHORIZATION_PROOF_VERIFIER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "IDENTITY_CONSTRUCTION_PROOF_VERIFIER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "IDENTITY_MEMBERSHIP_PROOF_VERIFIER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256[2]",
                name: "a",
                type: "uint256[2]",
              },
              {
                internalType: "uint256[2][2]",
                name: "b",
                type: "uint256[2][2]",
              },
              {
                internalType: "uint256[2]",
                name: "c",
                type: "uint256[2]",
              },
            ],
            internalType: "struct IKeyringZkVerifier.Groth16Proof",
            name: "proof",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "root",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nullifierHash",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "signalHash",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "externalNullifier",
            type: "uint256",
          },
        ],
        internalType: "struct IKeyringZkVerifier.IdentityMembershipProof",
        name: "membershipProof",
        type: "tuple",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "uint256[2]",
                name: "a",
                type: "uint256[2]",
              },
              {
                internalType: "uint256[2][2]",
                name: "b",
                type: "uint256[2][2]",
              },
              {
                internalType: "uint256[2]",
                name: "c",
                type: "uint256[2]",
              },
            ],
            internalType: "struct IKeyringZkVerifier.Groth16Proof",
            name: "proof",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "externalNullifier",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nullifierHash",
            type: "uint256",
          },
          {
            internalType: "uint256[2]",
            name: "policyDisclosures",
            type: "uint256[2]",
          },
          {
            internalType: "uint256",
            name: "tradingAddress",
            type: "uint256",
          },
        ],
        internalType: "struct IKeyringZkVerifier.IdentityAuthorisationProof",
        name: "authorisationProof",
        type: "tuple",
      },
    ],
    name: "checkClaim",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256[2]",
                name: "a",
                type: "uint256[2]",
              },
              {
                internalType: "uint256[2][2]",
                name: "b",
                type: "uint256[2][2]",
              },
              {
                internalType: "uint256[2]",
                name: "c",
                type: "uint256[2]",
              },
            ],
            internalType: "struct IKeyringZkVerifier.Groth16Proof",
            name: "proof",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "externalNullifier",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nullifierHash",
            type: "uint256",
          },
          {
            internalType: "uint256[2]",
            name: "policyDisclosures",
            type: "uint256[2]",
          },
          {
            internalType: "uint256",
            name: "tradingAddress",
            type: "uint256",
          },
        ],
        internalType: "struct IKeyringZkVerifier.IdentityAuthorisationProof",
        name: "authorisationProof",
        type: "tuple",
      },
    ],
    name: "checkIdentityAuthorisationProof",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256[2]",
                name: "a",
                type: "uint256[2]",
              },
              {
                internalType: "uint256[2][2]",
                name: "b",
                type: "uint256[2][2]",
              },
              {
                internalType: "uint256[2]",
                name: "c",
                type: "uint256[2]",
              },
            ],
            internalType: "struct IKeyringZkVerifier.Groth16Proof",
            name: "proof",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "identity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "policyCommitment",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxAddresses",
            type: "uint256",
          },
        ],
        internalType: "struct IKeyringZkVerifier.IdentityConstructionProof",
        name: "constructionProof",
        type: "tuple",
      },
    ],
    name: "checkIdentityConstructionProof",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256[2]",
                name: "a",
                type: "uint256[2]",
              },
              {
                internalType: "uint256[2][2]",
                name: "b",
                type: "uint256[2][2]",
              },
              {
                internalType: "uint256[2]",
                name: "c",
                type: "uint256[2]",
              },
            ],
            internalType: "struct IKeyringZkVerifier.Groth16Proof",
            name: "proof",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "root",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nullifierHash",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "signalHash",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "externalNullifier",
            type: "uint256",
          },
        ],
        internalType: "struct IKeyringZkVerifier.IdentityMembershipProof",
        name: "membershipProof",
        type: "tuple",
      },
    ],
    name: "checkIdentityMembershipProof",
    outputs: [
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKeyringZkVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IKeyringZkVerifierInterface {
    return new utils.Interface(_abi) as IKeyringZkVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKeyringZkVerifier {
    return new Contract(address, _abi, signerOrProvider) as IKeyringZkVerifier;
  }
}
