/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKeyringGuard,
  IKeyringGuardInterface,
} from "../../../../contracts/keyring/interfaces/IKeyringGuard";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "Unacceptable",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "keyringCredentials",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "policyManager",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "userPolicies",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "admissionPolicyId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "universeRule",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "emptyRule",
        type: "bytes32",
      },
    ],
    name: "KeyringGuardConfigured",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "WhitelistAddress",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "trader",
        type: "address",
      },
    ],
    name: "checkCache",
    outputs: [
      {
        internalType: "bool",
        name: "isIndeed",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "checkGuard",
    outputs: [
      {
        internalType: "bool",
        name: "isAuthorized",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "checkAddress",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "isIndeed",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "whitelistAddressAtIndex",
    outputs: [
      {
        internalType: "address",
        name: "whitelisted",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "whitelistAddressCount",
    outputs: [
      {
        internalType: "uint256",
        name: "count",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKeyringGuard__factory {
  static readonly abi = _abi;
  static createInterface(): IKeyringGuardInterface {
    return new utils.Interface(_abi) as IKeyringGuardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKeyringGuard {
    return new Contract(address, _abi, signerOrProvider) as IKeyringGuard;
  }
}
