/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as profiles from "./profiles";
export type { profiles };
export type { Resolver } from "./Resolver";
